analytics: {}
color:
  brandColors: []
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0.008445
cta: {}
layout_spectrum: 0.97591
name: ruckusiznecessary
opengraph: {}
purpose: {}
typography_spectrum: 0.471284
